name: pigeon_filter
description: Filter classified isoforms based on SQANTI3 attributes.
keywords:
  - isoseq
  - pigeon
  - filter
  - transcriptome
  - pacbio
tools:
  - pigeon:
      description: Transcript Toolkit for classification and filtering of Iso-Seq data.
      homepage: https://isoseq.how/pigeon/
      documentation: https://isoseq.how/pigeon/
      licence: ["PacBio"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - classification:
      type: file
      description: Classification results from pigeon classify.
      pattern: "*.classification.txt"
  - gff:
      type: file
      description: The original isoforms GFF file to be filtered.
      pattern: "*.gff"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - classification:
      type: file
      description: Filtered classification results.
      pattern: "*_filtered_classification.txt"
  - gff:
      type: file
      description: Filtered isoforms GFF file.
      pattern: "*_filtered.gff"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@aidantay"
